[package]
name = "rcmd-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rcmd"
path = "src/main.rs"

[features]
default = ["syntax"]
syntax = ["rcmd-edit/syntax"]

[dependencies]
rcmd-core = { path = "../rcmd-core" }
rcmd-edit = { path = "../rcmd-edit" }
anyhow.workspace = true
ratatui.workspace = true
chrono.workspace = true
libc.workspace = true
serde.workspace = true
toml.workspace = true
notify.workspace = true
